# Generated by Django 3.0.6 on 2020-06-25 08:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('whoami', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='text_workExperience',
            field=tinymce.models.HTMLField(),
        ),
    ]
