# Generated by Django 3.0.6 on 2020-06-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0003_auto_20200623_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
    ]
