# Generated by Django 3.0.6 on 2020-06-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0004_remove_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Description'),
        ),
    ]
